# cluster_slurm.yaml for CRAMboozle.snakefile, for use on Fred Hutch servers
# (modfiy to fit your own needs if using snakemake in another setting)
# Robert Patton, rpatton@fredhutch.org (Ha Lab)
# v1.0

__default__:
    partition: campus-new
    time: "72:0:0"
    mem: 128G
    ncpus: 16
    ntasks: 1
    output: logs/cluster/{rule}.%A.out
    JobName: "{rule}"

cramboozle:
    partition: campus-new
    mem: 128G # defaults to 4Gb x ncpus
    ncpus: 16 # number of cores to process each sample
    output: logs/cluster/{rule}.{wildcards.samples}.%A.out
    JobName: "{rule}.{wildcards.samples}"
