# CRAMboozle Configuration File
# Robert Patton, rpatton@fredhutch.org (Ha Lab)
# v1.0 - Configuration for de-identifying BAM/CRAM files

################
# config files #
################

cluster_slurm: config/cluster_slurm.yaml # used to get info about available CPUs

##############
# parameters #
##############

# Reference genome FASTA file (required for CRAM files)
reference_genome: /fh/fast/ha_g/grp/reference/GRCh38/Broad_bundle_hg38/v0/Homo_sapiens_assembly38.fasta # standard choice for DNA sequencing in Ha lab
# reference_genome: /fh/fast/ha_g/grp/reference/Release_33_GRCh38/GRCh38.primary_assembly.genome.fa #  alt reference for most RNA-Seq

# Results directory where de-identified files will be saved
results_dir: results # where your results will go

# Processing options
strict_mode: false        # Enable strict mode for additional tag sanitization
keep_unmapped: false      # Keep unmapped reads in output
keep_secondary: false     # Keep secondary alignments in output
